title: Green Party Conference Agenda
description: >-
  Motions for the Green Party Conferences, brought to you by the Standing Orders Committee.
email: soc@greenparty.org.uk
baseurl: ""
url: "http://greencoordinate.co.uk"

# Switches
affiliated_threshold: 4 # The number of coproposers needed for an affiliated motion to be debated.
unaffiliated_threshold: 12 # The number of coproposers needed for an unaffiliated motion to be debated.
create_sections: true # If true, display each section as a separate list.
show_coproposers: false # If true, list the coproposers for each motion.
archive_notice: false # If true, prepend each page with "archive_notice.html".
archive_mode: false # If true, replace the homepage with a list of archived conferences.

# Build settings
sass:
  sass_dir: /css/

collections:
  amendments:
    output: false
  motions:
    output: true
    permalink: :collection/:name/


defaults:
  - scope:
      path: ""
      type: "motions"
    values:
      layout: "motion"
      toc: true

include: ["_redirects"]
